extension BiblePlaceHolder on String {
  String biblePlaceHolder() => 'assets/images/placeholder.png';
}

extension BibleItemAssets on String {
  String bibleItemAssets() {
    switch (this) {
      case '창':
        return 'assets/images/bg_gn_test.jpg';
      case '출':
        return 'assets/images/bg_test.jpg';
      case '레':
        return 'assets/images/bg_test.jpg';
      case '민':
        return 'assets/images/bg_test.jpg';
      case '신':
        return 'assets/images/bg_test.jpg';
      case '수':
        return 'assets/images/bg_test.jpg';
      case '삿':
        return 'assets/images/bg_test.jpg';
      case '룻':
        return 'assets/images/bg_test.jpg';
      case '삼상':
        return 'assets/images/bg_test.jpg';
      case '삼하':
        return 'assets/images/bg_test.jpg';
      case '왕상':
        return 'assets/images/bg_test.jpg';
      case '왕하':
        return 'assets/images/bg_test.jpg';
      case '대상':
        return 'assets/images/bg_test.jpg';
      case '대하':
        return 'assets/images/bg_test.jpg';
      case '스':
        return 'assets/images/bg_test.jpg';
      case '느':
        return 'assets/images/bg_test.jpg';
      case '에':
        return 'assets/images/bg_test.jpg';
      case '욥':
        return 'assets/images/bg_test.jpg';
      case '시':
        return 'assets/images/bg_test.jpg';
      case '잠':
        return 'assets/images/bg_test.jpg';
      case '전':
        return 'assets/images/bg_test.jpg';
      case '아':
        return 'assets/images/bg_test.jpg';
      case '사':
        return 'assets/images/bg_test.jpg';
      case '렘':
        return 'assets/images/bg_test.jpg';
      case '애':
        return 'assets/images/bg_test.jpg';
      case '겔':
        return 'assets/images/bg_test.jpg';
      case '단':
        return 'assets/images/bg_test.jpg';
      case '호':
        return 'assets/images/bg_test.jpg';
      case '욜':
        return 'assets/images/bg_test.jpg';
      case '암':
        return 'assets/images/bg_test.jpg';
      case '옵':
        return 'assets/images/bg_test.jpg';
      case '욘':
        return 'assets/images/bg_test.jpg';
      case '미':
        return 'assets/images/bg_test.jpg';
      case '나':
        return 'assets/images/bg_test.jpg';
      case '합':
        return 'assets/images/bg_test.jpg';
      case '습':
        return 'assets/images/bg_test.jpg';
      case '학':
        return 'assets/images/bg_test.jpg';
      case '슥':
        return 'assets/images/bg_test.jpg';
      case '말':
        return 'assets/images/bg_test.jpg';
      case '마':
        return 'assets/images/bg_test.jpg';
      case '막':
        return 'assets/images/bg_test.jpg';
      case '눅':
        return 'assets/images/bg_test.jpg';
      case '요':
        return 'assets/images/bg_test.jpg';
      case '행':
        return 'assets/images/bg_test.jpg';
      case '롬':
        return 'assets/images/bg_test.jpg';
      case '고전':
        return 'assets/images/bg_test.jpg';
      case '고후':
        return 'assets/images/bg_test.jpg';
      case '갈':
        return 'assets/images/bg_test.jpg';
      case '엡':
        return 'assets/images/bg_test.jpg';
      case '빌':
        return 'assets/images/bg_test.jpg';
      case '골':
        return 'assets/images/bg_test.jpg';
      case '살전':
        return 'assets/images/bg_test.jpg';
      case '살후':
        return 'assets/images/bg_test.jpg';
      case '딤전':
        return 'assets/images/bg_test.jpg';
      case '딤후':
        return 'assets/images/bg_test.jpg';
      case '딛':
        return 'assets/images/bg_test.jpg';
      case '몬':
        return 'assets/images/bg_test.jpg';
      case '히':
        return 'assets/images/bg_test.jpg';
      case '약':
        return 'assets/images/bg_test.jpg';
      case '벧전':
        return 'assets/images/bg_test.jpg';
      case '벧후':
        return 'assets/images/bg_test.jpg';
      case '요일':
        return 'assets/images/bg_test.jpg';
      case '요이':
        return 'assets/images/bg_test.jpg';
      case '요삼':
        return 'assets/images/bg_test.jpg';
      case '유':
        return 'assets/images/bg_test.jpg';
      case '계':
        return 'assets/images/bg_test.jpg';

      default:
        return 'assets/images/placeholder.png';
    }
  }
}
